# These are supported funding model platforms

github: https://github.com/lnginyard
patreon: https://patreon.com/lnginyard
open_collective: https://opencollective.com/lorenzo-ginyard
ko_fi: https://ko-fi.com/lorenzoginyard
paypal: https://paypal.com/zotech1
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
